title: My Notes
description: My personal notes

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - setup_pages.py
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
